name: Install Xvfb

runs:
  using: "composite"
  steps:
    - name: Install Xvfb
      shell: bash -l {0}
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      shell: bash -l {0}
      run: sudo Xvfb :1 -ac -screen 0 1024x768x24 &