version: "3.8"

services:
  wave:
    image: wave-${BASE_OS}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./dockerfiles/${BASE_OS}/Dockerfile

  test:
    image: wave-${BASE_OS}:${IMAGE_TAG}
    command: ["test"]

