services:
  wave:
    image: wave:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - 3002:3002

  test:
    image: wave:${IMAGE_TAG}
    command: ["test"]
    volumes:
      - ./src/:/opt/app/src
      - ./tests/:/opt/app/tests
