#!/bin/bash

basedir=tests/__tests__/__snapshots__
expected=.expected.png
actual=.actual.png
save=.save.png

if [[ "$1" == "forward" ]]; then
    echo "Saving existing expected images"
    for fl in `ls ${basedir}/*${expected}`; do
        basename=${fl/${basedir}\//}
        rootname=${basename/${expected}/}
        cp ${basedir}/${basename} ${basedir}/${rootname}${save}
    done
    
    echo "Copying actual images to expected (if they exist)"
    for fl in `ls ${basedir}/*${actual}`; do
        basename=${fl/${basedir}\//}
        rootname=${basename/${actual}/}
        cp ${basedir}/${basename} ${basedir}/${rootname}${expected}
    done
elif [[ "$1" == "backward" ]]; then
    echo "Moving saved images back to expected"
    for fl in `ls ${basedir}/*${save}`; do
        basename=${fl/${basedir}\//}
        rootname=${basename/${save}/}
        mv ${basedir}/${basename} ${basedir}/${rootname}${expected}
    done
else
    echo "
Due to inconsistencies in the treatment of line objects in WebGL, there is no
guarantee that a given system configuration produces identical PNGs for objects
using THREE.Line objects (including all the unit cells in the expected images).
This script migrates actual images to expected images so one can run tests on
MacOS.

Note:
    If run, these new expected images should *NOT* be committed, as the lines
    generated by the CentOS-based container are correct for CI testing.

Please provide an argument [forward|backward]
"
fi
