name: Build docker container and run tests
inputs:
  base-os:
    description: Which OS Dockerfile to use
    required: true

runs:
  using: composite
  steps:
    - name: Build container
      shell: bash -l {0}
      run: BASE_OS=${{ inputs.base-os }} docker-compose build

    - name: Run tests
      shell: bash -l {0}
      run: BASE_OS=${{ inputs.base-os }} docker-compose run test
