name: Build docker container and run tests
description: Assumes actions repository has been checked out
inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true

runs:
  using: composite
  steps:
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.3.6
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('package.json') }}

    # - name: Pull base image
    #   uses: ./actions/docker/ecr
    #   id: login-ecr
    #   with:
    #     ecr-repository: centos-7.9-base
    #     aws-access-key-id: ${{ inputs.aws-access-key-id }}
    #     aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
    #     image-tag: latest
    #     action: pull

    - name: Build base image
      uses: ./actions/docker/build
      with:
        image-name: ghcr.io/exabyte-io/centos-7.9-base-materials-designer
        dockerfile: ./dockerfiles/centos/Dockerfile

    - name: Push updated application container
      shell: bash -l {0}
      run: |
        docker push ghcr.io/exabyte-io/centos-7.9-base-materials-designer:latest

    - name: Build container
      uses: ./actions/docker/build
      with:
        image-name: wave-test
        dockerfile: ./dockerfiles/app/Dockerfile
        cli-args: --build-arg BASE_IMAGE=ghcr.io/exabyte-io/centos-7.9-base-materials-designer

    - name: Run tests
      shell: bash -l {0}
      run: docker run --env REACT_APP_BASE_OS=centos wave-test:latest test
