name: CICD

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
            repository: Exabyte-io/actions
            token: ${{ secrets.BOT_GITHUB_TOKEN }}
            path: actions

      - name: Install Xvfb
        uses: ./.github/workflows/install-xvfb

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run: npm install

      - name: Run tests
        run: sudo xvfb-run -s "-ac -screen 0 1024x768x24" npx jest tests/__tests__/wave.js

      - name: Cleanup Xvfb
        if: ${{  always() }}
        uses: ./.github/workflows/cleanup-xvfb


  publish:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish release
        uses: ./actions/js/publish
        with:
          node-version: 12.21.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
