name: Run containerized tests and publish to NPM on branch == 'dev'

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: feature/SOF-5466
          path: actions

      - name: Validate JS package
        uses: ./actions/js/validate

      - name: Build and test
        uses: ./.github/workflows/docker-build-test
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  publish:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Build and test
        uses: ./.github/workflows/docker-build-test
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Publish release
        uses: ./actions/js/publish
        with:
          node-version: 12.21.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          verify-tests: 'false'
