---

name: Publish WIP release tarball

on: push

jobs:
  release-wip:
    uses: mat3ra/actions/.github/workflows/release-wip.yml@main
    with:
      package-name: wave.js
      build-script: transpile
    secrets:
      github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
